POST http://localhost:8080/api/category
Content-Type: application/json

{
  "id": "",
  "categoryName": "Grocery",
  "description": "These are all Grocery Product."
}

###
POST http://localhost:8080/api/category/search
Content-Type: application/json

{
  "page": 0,
  "size": 10
}